wandb_version: 1

_name_or_path:
  desc: null
  value: google/mt5-small
_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: huggingface
    huggingface_version: 4.38.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: train/global_step
      6:
      - 3
    - 1: train/loss
      5: 1
      6:
      - 1
    - 1: train/grad_norm
      5: 1
      6:
      - 1
    - 1: train/learning_rate
      5: 1
      6:
      - 1
    - 1: train/epoch
      5: 1
      6:
      - 1
    python_version: 3.10.6
    start_time: 1714098237.736772
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 7
      - 23
      4: 3.10.6
      5: 0.13.9
      6: 4.38.2
      8:
      - 5
      9:
        1: transformers_trainer
accelerator_config:
  desc: null
  value:
    dispatch_batches: null
    even_batches: true
    split_batches: false
    use_seedable_sampler: true
adafactor:
  desc: null
  value: false
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
add_cross_attention:
  desc: null
  value: false
architectures:
  desc: null
  value:
  - MT5ForConditionalGeneration
auto_find_batch_size:
  desc: null
  value: false
bad_words_ids:
  desc: null
  value: null
begin_suppress_tokens:
  desc: null
  value: null
bf16:
  desc: null
  value: false
bf16_full_eval:
  desc: null
  value: false
bos_token_id:
  desc: null
  value: null
chunk_size_feed_forward:
  desc: null
  value: 0
classifier_dropout:
  desc: null
  value: 0.0
cross_attention_hidden_size:
  desc: null
  value: null
d_ff:
  desc: null
  value: 1024
d_kv:
  desc: null
  value: 64
d_model:
  desc: null
  value: 512
data_seed:
  desc: null
  value: null
dataloader_drop_last:
  desc: null
  value: false
dataloader_num_workers:
  desc: null
  value: 0
dataloader_persistent_workers:
  desc: null
  value: false
dataloader_pin_memory:
  desc: null
  value: true
dataloader_prefetch_factor:
  desc: null
  value: null
ddp_backend:
  desc: null
  value: null
ddp_broadcast_buffers:
  desc: null
  value: null
ddp_bucket_cap_mb:
  desc: null
  value: null
ddp_find_unused_parameters:
  desc: null
  value: null
ddp_timeout:
  desc: null
  value: 1800
debug:
  desc: null
  value: []
decoder_start_token_id:
  desc: null
  value: 0
deepspeed:
  desc: null
  value: null
dense_act_fn:
  desc: null
  value: gelu_new
disable_tqdm:
  desc: null
  value: false
dispatch_batches:
  desc: null
  value: null
diversity_penalty:
  desc: null
  value: 0.0
do_eval:
  desc: null
  value: true
do_predict:
  desc: null
  value: false
do_sample:
  desc: null
  value: false
do_train:
  desc: null
  value: true
dropout_rate:
  desc: null
  value: 0.1
early_stopping:
  desc: null
  value: false
encoder_no_repeat_ngram_size:
  desc: null
  value: 0
eos_token_id:
  desc: null
  value: 1
eval_accumulation_steps:
  desc: null
  value: null
eval_delay:
  desc: null
  value: 0
eval_steps:
  desc: null
  value: 5000
evaluation_strategy:
  desc: null
  value: steps
exponential_decay_length_penalty:
  desc: null
  value: null
feed_forward_proj:
  desc: null
  value: gated-gelu
finetuning_task:
  desc: null
  value: null
forced_bos_token_id:
  desc: null
  value: null
forced_eos_token_id:
  desc: null
  value: null
fp16:
  desc: null
  value: false
fp16_backend:
  desc: null
  value: auto
fp16_full_eval:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
fsdp:
  desc: null
  value: []
fsdp_config:
  desc: null
  value:
    min_num_params: 0
    xla: false
    xla_fsdp_grad_ckpt: false
    xla_fsdp_v2: false
fsdp_min_num_params:
  desc: null
  value: 0
fsdp_transformer_layer_cls_to_wrap:
  desc: null
  value: null
full_determinism:
  desc: null
  value: false
generation_config:
  desc: null
  value: null
generation_max_length:
  desc: null
  value: null
generation_num_beams:
  desc: null
  value: null
gradient_accumulation_steps:
  desc: null
  value: 1
gradient_checkpointing:
  desc: null
  value: false
gradient_checkpointing_kwargs:
  desc: null
  value: null
greater_is_better:
  desc: null
  value: null
group_by_length:
  desc: null
  value: false
half_precision_backend:
  desc: null
  value: auto
hub_always_push:
  desc: null
  value: false
hub_model_id:
  desc: null
  value: null
hub_private_repo:
  desc: null
  value: false
hub_strategy:
  desc: null
  value: every_save
hub_token:
  desc: null
  value: <HUB_TOKEN>
id2label:
  desc: null
  value:
    '0': LABEL_0
    '1': LABEL_1
ignore_data_skip:
  desc: null
  value: false
include_inputs_for_metrics:
  desc: null
  value: false
include_num_input_tokens_seen:
  desc: null
  value: false
include_tokens_per_second:
  desc: null
  value: false
initializer_factor:
  desc: null
  value: 1.0
is_decoder:
  desc: null
  value: false
is_encoder_decoder:
  desc: null
  value: true
is_gated_act:
  desc: null
  value: true
jit_mode_eval:
  desc: null
  value: false
label2id:
  desc: null
  value:
    LABEL_0: 0
    LABEL_1: 1
label_names:
  desc: null
  value: null
label_smoothing_factor:
  desc: null
  value: 0.0
layer_norm_epsilon:
  desc: null
  value: 1.0e-06
learning_rate:
  desc: null
  value: 2.0e-05
length_column_name:
  desc: null
  value: length
length_penalty:
  desc: null
  value: 1.0
load_best_model_at_end:
  desc: null
  value: false
local_rank:
  desc: null
  value: 0
log_level:
  desc: null
  value: passive
log_level_replica:
  desc: null
  value: warning
log_on_each_node:
  desc: null
  value: true
logging_dir:
  desc: null
  value: /mmfs1/gscratch/ark/knylund/bad-pair-encoding/mt_models/mt5-small_English-German_default_tokenizer/runs/Apr25_19-23-15_g3094
logging_first_step:
  desc: null
  value: false
logging_nan_inf_filter:
  desc: null
  value: true
logging_steps:
  desc: null
  value: 500
logging_strategy:
  desc: null
  value: steps
lr_scheduler_kwargs:
  desc: null
  value: {}
lr_scheduler_type:
  desc: null
  value: linear
max_grad_norm:
  desc: null
  value: 1.0
max_length:
  desc: null
  value: 20
max_steps:
  desc: null
  value: -1
metric_for_best_model:
  desc: null
  value: null
min_length:
  desc: null
  value: 0
model_type:
  desc: null
  value: mt5
mp_parameters:
  desc: null
  value: ''
neftune_noise_alpha:
  desc: null
  value: null
no_cuda:
  desc: null
  value: false
no_repeat_ngram_size:
  desc: null
  value: 0
num_beam_groups:
  desc: null
  value: 1
num_beams:
  desc: null
  value: 1
num_decoder_layers:
  desc: null
  value: 8
num_heads:
  desc: null
  value: 6
num_layers:
  desc: null
  value: 8
num_return_sequences:
  desc: null
  value: 1
num_train_epochs:
  desc: null
  value: 1
optim:
  desc: null
  value: adamw_torch
optim_args:
  desc: null
  value: null
output_attentions:
  desc: null
  value: false
output_dir:
  desc: null
  value: /mmfs1/gscratch/ark/knylund/bad-pair-encoding/mt_models/mt5-small_English-German_default_tokenizer
output_hidden_states:
  desc: null
  value: false
output_scores:
  desc: null
  value: false
overwrite_output_dir:
  desc: null
  value: false
pad_token_id:
  desc: null
  value: 0
past_index:
  desc: null
  value: -1
per_device_eval_batch_size:
  desc: null
  value: 16
per_device_train_batch_size:
  desc: null
  value: 16
per_gpu_eval_batch_size:
  desc: null
  value: null
per_gpu_train_batch_size:
  desc: null
  value: null
predict_with_generate:
  desc: null
  value: true
prediction_loss_only:
  desc: null
  value: false
prefix:
  desc: null
  value: null
problem_type:
  desc: null
  value: null
pruned_heads:
  desc: null
  value: {}
push_to_hub:
  desc: null
  value: false
push_to_hub_model_id:
  desc: null
  value: null
push_to_hub_organization:
  desc: null
  value: null
push_to_hub_token:
  desc: null
  value: <PUSH_TO_HUB_TOKEN>
ray_scope:
  desc: null
  value: last
relative_attention_max_distance:
  desc: null
  value: 128
relative_attention_num_buckets:
  desc: null
  value: 32
remove_invalid_values:
  desc: null
  value: false
remove_unused_columns:
  desc: null
  value: true
repetition_penalty:
  desc: null
  value: 1.0
report_to:
  desc: null
  value:
  - wandb
resume_from_checkpoint:
  desc: null
  value: null
return_dict:
  desc: null
  value: true
return_dict_in_generate:
  desc: null
  value: false
run_name:
  desc: null
  value: /mmfs1/gscratch/ark/knylund/bad-pair-encoding/mt_models/mt5-small_English-German_default_tokenizer
save_on_each_node:
  desc: null
  value: false
save_only_model:
  desc: null
  value: false
save_safetensors:
  desc: null
  value: true
save_steps:
  desc: null
  value: 500
save_strategy:
  desc: null
  value: steps
save_total_limit:
  desc: null
  value: 3
seed:
  desc: null
  value: 42
sep_token_id:
  desc: null
  value: null
skip_memory_metrics:
  desc: null
  value: true
sortish_sampler:
  desc: null
  value: false
split_batches:
  desc: null
  value: null
suppress_tokens:
  desc: null
  value: null
task_specific_params:
  desc: null
  value: null
temperature:
  desc: null
  value: 1.0
tf32:
  desc: null
  value: null
tf_legacy_loss:
  desc: null
  value: false
tie_encoder_decoder:
  desc: null
  value: false
tie_word_embeddings:
  desc: null
  value: false
tokenizer_class:
  desc: null
  value: T5Tokenizer
top_k:
  desc: null
  value: 50
top_p:
  desc: null
  value: 1.0
torch_compile:
  desc: null
  value: false
torch_compile_backend:
  desc: null
  value: null
torch_compile_mode:
  desc: null
  value: null
torch_dtype:
  desc: null
  value: null
torchdynamo:
  desc: null
  value: null
torchscript:
  desc: null
  value: false
tpu_metrics_debug:
  desc: null
  value: false
tpu_num_cores:
  desc: null
  value: null
transformers_version:
  desc: null
  value: 4.38.2
typical_p:
  desc: null
  value: 1.0
use_bfloat16:
  desc: null
  value: false
use_cache:
  desc: null
  value: true
use_cpu:
  desc: null
  value: false
use_ipex:
  desc: null
  value: false
use_legacy_prediction_loop:
  desc: null
  value: false
use_mps_device:
  desc: null
  value: false
vocab_size:
  desc: null
  value: 250112
warmup_ratio:
  desc: null
  value: 0.0
warmup_steps:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 0.01
